# Generated by Django 6.0.1 on 2026-02-20 23:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshroom', '0002_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='understory/galerina_marginata.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='article',
            name='shroom',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
