# Generated by Django 6.0.1 on 2026-02-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshroom', '0003_article_image_article_shroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(max_length=250, unique_for_date='publish'),
        ),
    ]
