# Generated by Django 6.0.1 on 2026-02-25 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newshroom', '0004_alter_article_image_alter_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='shroom',
        ),
    ]
