# Generated by Django 6.0.1 on 2026-02-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshroom', '0007_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
