# Generated by Django 6.0.1 on 2026-04-11 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshroom', '0008_request_updated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='spotted_by',
            field=models.ManyToManyField(blank=True, related_name='newshroom_spotted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='total_spots',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
