# Generated by Django 6.0.1 on 2026-04-11 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('source_url', models.URLField()),
                ('image', models.ImageField(upload_to='specimens/%Y/%m/%d/')),
                ('description', models.TextField(blank=True)),
                ('collected_on', models.DateField(auto_now_add=True)),
                ('total_spots', models.PositiveIntegerField(default=0)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sporebrint_collected', to=settings.AUTH_USER_MODEL)),
                ('spotted_by', models.ManyToManyField(blank=True, related_name='sporeprint_spotted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-collected_on'],
                'indexes': [models.Index(fields=['-collected_on'], name='sporeprint__collect_bad365_idx'), models.Index(fields=['-total_spots'], name='sporeprint__total_s_3ff4ec_idx')],
            },
        ),
    ]
