# Generated by Django 6.0.1 on 2026-04-12 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mycoguide', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForagingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='foraging_reports',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('location', models.CharField(max_length=250)),
                ('date_foraged', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='fieldnotes__created_2db866_idx')],
            },
        ),
        migrations.CreateModel(
            name='ForagingReportSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fieldnotes.foragingreport')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_items', to='mycoguide.mushroomspecies')),
            ],
        ),
    ]
