# Generated by Django 6.0.1 on 2026-04-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldnotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foragingreportspecies',
            name='condition',
            field=models.CharField(blank=True, choices=[('FR', 'Fresh'), ('WT', 'Weathered'), ('DM', 'Damaged'), ('IN', 'Inedible')], max_length=2),
        ),
        migrations.AddField(
            model_name='foragingreportspecies',
            name='growth_stage',
            field=models.CharField(blank=True, choices=[('BT', 'Button'), ('PN', 'Pin'), ('MT', 'Mature'), ('PS', 'Past Prime')], max_length=2),
        ),
        migrations.AddField(
            model_name='foragingreportspecies',
            name='habitat_context',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='foragingreportspecies',
            name='toxicity',
            field=models.CharField(blank=True, choices=[('ED', 'Edible 😋'), ('MD', 'Mildly Toxic 😣'), ('MO', 'Moderately Toxic 🤢'), ('SE', 'Severely Toxic 🤮'), ('DD', 'Deadly 💀')], max_length=2),
        ),
    ]
