# Generated by Django 6.0.1 on 2026-04-15 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fieldnotes', '0002_foragingreportspecies_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foragingreportspecies',
            name='toxicity',
        ),
    ]
