# Generated by Django 6.0.1 on 2026-04-11 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairy_ring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForagerConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('forager_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fairy_ring.profile')),
                ('forager_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followed_by', through='fairy_ring.ForagerConnection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='foragerconnection',
            index=models.Index(fields=['-created'], name='fairy_ring__created_eabeab_idx'),
        ),
        migrations.AddConstraint(
            model_name='foragerconnection',
            constraint=models.UniqueConstraint(fields=('forager_from', 'forager_to'), name='unique_forager_connection'),
        ),
    ]
