# Generated by Django 6.0.1 on 2026-04-11 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairy_ring', '0002_foragerconnection_profile_following_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
        migrations.AlterField(
            model_name='foragerconnection',
            name='forager_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follwoing', to=settings.AUTH_USER_MODEL),
        ),
    ]
