# Generated by Django 6.0.1 on 2026-04-12 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MushroomGenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'genus',
                'verbose_name_plural': 'genera',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='mycoguide_m_name_a72213_idx')],
            },
        ),
        migrations.CreateModel(
            name='MushroomSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='species/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('edibility', models.CharField(choices=[('edible', 'Edible'), ('caution', 'Edible with Caution'), ('inedible', 'Inedible'), ('toxic', 'Toxic'), ('deadly', 'Deadly')], default='inedible', max_length=20)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='mycoguide.mushroomgenus')),
            ],
            options={
                'verbose_name_plural': 'species',
                'ordering': ['common_name'],
                'indexes': [models.Index(fields=['id', 'slug'], name='mycoguide_m_id_c586ba_idx'), models.Index(fields=['common_name'], name='mycoguide_m_common__893ef6_idx'), models.Index(fields=['-created'], name='mycoguide_m_created_e3d312_idx')],
            },
        ),
    ]
