# Generated by Django 6.0.4 on 2026-04-21 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('pronouns_1', models.CharField(blank=True, choices=[('NB1', 'They'), ('NB2', 'Them'), ('FM1', 'She'), ('FM2', 'Her'), ('MA1', 'He'), ('MA2', 'Him'), ('NE1', 'Ze'), ('NE2', 'Hir'), ('NEW', 'Other')], default=None, max_length=3, null=True)),
                ('pronouns_2', models.CharField(blank=True, choices=[('NB1', 'They'), ('NB2', 'Them'), ('FM1', 'She'), ('FM2', 'Her'), ('MA1', 'He'), ('MA2', 'Him'), ('NE1', 'Ze'), ('NE2', 'Hir'), ('NEW', 'Other')], default=None, max_length=3, null=True)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('pronouns_1', models.CharField(blank=True, choices=[('NB1', 'They'), ('NB2', 'Them'), ('FM1', 'She'), ('FM2', 'Her'), ('MA1', 'He'), ('MA2', 'Him'), ('NE1', 'Ze'), ('NE2', 'Hir'), ('NEW', 'Other')], default=None, max_length=3, null=True)),
                ('pronouns_2', models.CharField(blank=True, choices=[('NB1', 'They'), ('NB2', 'Them'), ('FM1', 'She'), ('FM2', 'Her'), ('MA1', 'He'), ('MA2', 'Him'), ('NE1', 'Ze'), ('NE2', 'Hir'), ('NEW', 'Other')], default=None, max_length=3, null=True)),
                ('age_range', models.CharField(choices=[('<10', 'Under 10'), ('10-13', '10 to 13'), ('14-17', '14 to 17'), ('18+', '18 or older')], default=None)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='account_act_created_9dfed4_idx')],
            },
        ),
    ]
