# Generated by Django 6.0.1 on 2026-02-07 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('publish', models.DateTimeField(default=None)),
                ('title', models.CharField(max_length=250)),
                ('ref_url', models.CharField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='blog.article')),
            ],
            options={
                'ordering': ['-author'],
                'indexes': [models.Index(fields=['-author'], name='blog_refere_author_b9821d_idx')],
            },
        ),
    ]
