# Generated by Django 6.0.1 on 2026-02-07 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='ref_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(help_text='Section Header', max_length=50)),
                ('body', models.TextField(help_text='Section Content')),
                ('order', models.IntegerField(help_text='Order #')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='blog.article')),
            ],
            options={
                'ordering': ['-order'],
                'indexes': [models.Index(fields=['-order'], name='blog_sectio_order_1e1091_idx')],
            },
        ),
    ]
