# Generated by Django 6.0.1 on 2026-02-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_reference_ref_url_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='section',
            name='body',
            field=models.TextField(),
        ),
    ]
